-- AlterTable
ALTER TABLE `User` MODIFY `address` VARCHAR(191) NULL,
    MODIFY `birthday` VARCHAR(191) NULL,
    MODIFY `gender` VARCHAR(191) NULL,
    MODIFY `graduation` VARCHAR(191) NULL,
    MODIFY `ruby` VARCHAR(191) NULL,
    MODIFY `spouse` BOOLEAN NULL,
    MODIFY `tel` VARCHAR(191) NULL;
